name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build iOS App
        run: |
          xcodebuild \
            -project ChatApp.xcodeproj \
            -scheme ChatApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project ChatApp.xcodeproj \
            -scheme ChatApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            test
