name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Build iOS App
        run: |
          xcodebuild \
            -project ChatApp.xcodeproj \
            -scheme ChatApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            build

      - name: Check iOS Simulator
        run: |
          xcodebuild -version
          xcrun simctl list runtimes
          xcrun simctl list devices available
      
      - name: Boot iPhone 17 Simulator
        run: |
          xcrun simctl boot "iPhone 17" || true
          xcrun simctl bootstatus "iPhone 17" -b
      
      - name: Run Unit Tests
        timeout-minutes: 15
        run: |
          xcodebuild \
            -project ChatApp.xcodeproj \
            -scheme ChatApp \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.5' \
            -only-testing:ChatAppTests \
            test
